#!/bin/sh

while getopts ":c:m:j:i:" opt; do
  case $opt in
    c) >&2 echo "-c was triggered with paramter: $OPTARG." 
      classpath=$OPTARG
      ;;
    m) >&2 echo "-m was triggered with paramter: $OPTARG."  
       mainClass=$OPTARG
      ;;
    j) >&2 echo "-j was triggered with paramter: $OPTARG."  
       jarsHome=$OPTARG
      ;;
    i) >&2 echo "-i was triggered with paramter: $OPTARG."  
       input=$OPTARG
      ;;
    \?) >&2 echo "invalid options: -$OPTARG."
      ;;
    :) >&2 echo "option -$OPTARG requires a paramter."
      ;;
  esac
done


#jars
rt="/home/vijay/TestSubjects/jre1.7.0_55/lib/rt.jar"
guava=$jarsHome"/guava-14.0.1.jar"
asm=$jarsHome"/asm-all-4.0.jar"
junit=$jarsHome"/junit-4.11.jar"
xstream=$jarsHome"/xstream-1.4.4.jar"
xmlpull=$jarsHome"/xmlpull-1.1.3.1.jar"
blinky=$jarsHome"/blinky.jar"


# java -cp .:$classpath $mainClass $1

time java -Xbootclasspath/p:$asm:$blinky -cp .:$classpath -javaagent:$blinky $mainClass $input
