#!/bin/sh

blinky_args="xile"

while getopts ":c:m:j:i:ALM" opt; do
  case $opt in
    c) >&2 echo "-c was triggered with paramter: $OPTARG."
      classpath=$OPTARG
      ;;
    m) >&2 echo "-m was triggered with paramter: $OPTARG."
       mainClass=$OPTARG
      ;;
    j) >&2 echo "-j was triggered with paramter: $OPTARG."
       jarsHome=$OPTARG
      ;;
    i) >&2 echo "-i was triggered with paramter: $OPTARG."
       input=$OPTARG
      ;;
    A) >&2 echo "-A was triggered."
       blinky_args="xile"
      ;;
    L) >&2 echo "-L was triggered."
       blinky_args="l"
      ;;
    M) >&2 echo "-M was triggered."
       blinky_args="i"
      ;;
    \?) >&2 echo "invalid options: -$OPTARG."
      ;;
    :) >&2 echo "option -$OPTARG requires a paramter."
      ;;
  esac
done


#jars
asm=$jarsHome"/asm-all-4.0.jar"
blinky=$jarsHome"/blinky.jar"

>&2 echo "blinky_args are $blinky_args."

time java -Xbootclasspath/p:$asm:$blinky -cp .:$classpath -javaagent:$blinky=$blinky_args $mainClass $input
