#!/bin/sh
jars=/home/vijay/phd-open-source/blinky/jars
bin=/home/vijay/phd-open-source/blinky/bin
snitchMF=SnitchManifest
dataMF=DataManifest
controlMF=Manifest

cd $jars
pwd

cd $bin
jar cvfm $jars/blinky.jar $jars/Manifest org/spideruci
jar_result_id=$?
if [ $jar_result_id ]
then
	jar_message="Created"
else
	jar_message="... errr ... Something went worng."
fi

clear
pwd
echo blinky.jar $jar_message {jar_result_id - $jar_result_id}
echo blinky.jar $message {cp_result_id - $cp_result_id}
