#!/bin/bash

cd $1
mvn dependency:build-classpath -Dmdep.outputFile="cp.txt"
export CLASSPATH=`cat cp.txt`:$CLASSPATH
echo $CLASSPATH
export CLASSPATH=$1/target/test-classes:$1/target/classes:$CLASSPATH
echo $CLASSPATH

cd $2
mvn dependency:build-classpath -Dmdep.outputFile="cp.txt"
export CLASSPATH=`cat cp.txt`:$CLASSPATH
echo $CLASSPATH
export CLASSPATH=$2/target/test-classes:$2/target/classes:$CLASSPATH
echo $CLASSPATH
mvn dependency:copy-dependencies -DoutputDirectory=lib

java org.spideruci.analysis.dynamic.JunitRunner $1/target/test-classes