#!/bin/bash

instr_skip="instrumentation skipped for "
instr_fail="instrumentation failed for "
java_lang="java/lang"
org_spider_analysis="org/spideruci/analysis"
dacapo="dacapo"
harness="Harness"

while read p; do
  
  if [[ $p == $instr_skip* ]]; then
  	line=${p#$instr_skip}
  elif [[ $p == $instr_fail* ]]; then
  	line=${p#$instr_fail}
  else
  	continue
  	echo "not skipping this: $p"
  fi

  if [[ $line == $java_lang* ]] \
  	|| [[ $line == $org_spider_analysis* ]] \
  	|| [[ $line == $dacapo* ]] \
  	|| [[ $line == $harness ]]; then
  	continue
  fi

  echo $line

done < $1