#!/bin/bash

asm="/Users/vpalepu/.m2/repository/org/ow2/asm/asm-all/5.0/asm-all-5.0.jar"
blinkyjar="/Users/vpalepu/phd-open-source/blinky/target/blinky-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
# A,frames,retransform
blinky="-Xbootclasspath/p:$blinkyjar -javaagent:$blinkyjar=lIEx,frames"
blinky_only="-Xbootclasspath/p:$blinkyjar"
blinky_test="/Users/vpalepu/phd-open-source/blinky/target/blinky-0.0.1-SNAPSHOT-tests.jar"

java="/Users/vpalepu/open-source/java/jre1.7.0_60.jre/Contents/Home/bin/java"

cd ..

java $blinky -cp .:$blinky_test org.spideruci.analysis.dynamic.tests.Namaste > ./traces/namaste.trc 2> ./traces/namaste.err
java $blinky -cp .:$blinky_test org.spideruci.analysis.dynamic.tests.ControlStructureTests > ./traces/ControlStructureTests.trc 2> ./traces/ControlStructureTests.err

# ls -lh ./traces/$xmlfilename.trc
# less ./traces/$xmlfilename.trc ./traces/$xmlfilename.err