#!/bin/sh

while getopts ":c:j:i:" opt; do
  case $opt in
    c) >&2 echo "-c was triggered with paramter: $OPTARG."
      classpath=$OPTARG
      ;;
    j) >&2 echo "-j was triggered with paramter: $OPTARG."
       jarsHome=$OPTARG
      ;;
    i) >&2 echo "-i was triggered with paramter: $OPTARG."
       input=$OPTARG
      ;;
    \?) >&2 echo "invalid options: -$OPTARG."
      ;;
    :) >&2 echo "option -$OPTARG requires a paramter."
      ;;
  esac
done


#jars
rt="/home/vijay/TestSubjects/jre1.7.0_55/lib/rt.jar"
asm=$jarsHome"/asm-all-4.0.jar"
blinky=$jarsHome"/blinky.jar"
mainClass="org.spideruci.analysis.trace.TraceScanner"

# java -cp .:$classpath $mainClass $1

time java -cp .:$classpath:$asm:$blinky $mainClass $input
