#!/bin/bash

echo "# using blinky converting .trc files to .line.trc files."

subjects=("nanoxml" "javac" "jpacman" "jedit" "tetris" "jtopas")

echo "## Available Experimental Subjects:"
printf '%s\n' "${subjects[@]}"

trace_scanner="mvn exec:java -q -Ptracescanner -Dexec.args"
extn=".ltrc"
subject=$1
traces_path="/home/vpalepu/trace-clustering/$1/traces"
trace_count=$(ls -1 $traces_path/*.trc | wc -l)
echo ""
echo "subject: " $subject
echo "number of traces (.trc files): " $trace_count

cd blinky
for trace_file in $(ls $traces_path/*.trc)
do
	trace_name=$(echo $trace_file | cut -d'/' -f7)
	trace_name=$(echo $trace_name | cut -d'.' -f1)
	echo $trace_name$extn
	$trace_scanner"=$trace_file" > /home/share/trace-clustering/linetraces/$subject-$trace_name$extn
	echo $trace_file" done"
done
