## NOTE: if you are not going to add any elements to this list, then remove the list name as well.
exclusionList:
- java/
- sun
- apple/
- com/apple
- com/sun
- sunw
- sun
- javax/
- org/ietf
- org/jcp
- org/omg
- org/w3c
- org/xml
- org/objectweb/asm
- edu/uci/spiderlab/analysis
- org/spideruci/analysis
- test/
- Core/
- Data/
- dacapo
- Harness
- org/mockito
- org/hamcrest
- junit
- org/junit
- org/fest
- junit/tests/framework/
- junit/tests/runner/TextFeedbackTest
- junit/tests/runner/TextRunnerTest
- junit/tests/extensions

## NOTE: if you are not going to add any elements to this list, then remove the list name as well.
inclusionList:
- org/spideruci/patternabstraction/benckmark
- org/spideruci/analysis/diagnostics/subjects
- java/util/ArrayList

## FUTURE EXAMPLES (NOT YET TESTED; DO NOT UNCOMMENT):
# name: blinky
# number: !!int 1
# float: !!float 1.0
# boolen: !!bool true
# array: [1]
# LINE_COUNT: !!float 0.0