#!/bin/bash

BOLD=$(tput bold)
NORMAL=$(tput sgr0)
RED=$(tput setaf 1)

pwd
cat ./scripts/blinky


echo $String

echo "STARTING BLINKY DIAGNOSTICS"

# hmm ... ?
BLINKY_JAR="../blinky-core/target/blinky-core-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
DIAGNOSTICS_JAR="../blinky-diagnostics/target/blinky-diagnostics-0.0.1-SNAPSHOT-jar-with-dependencies.jar"

echo "Found Blinky Jar at following location:"
ls -alh $BLINKY_JAR

SUBJECTS_PKG="org.spideruci.analysis.diagnostics.subjects"
BLINKY="-Xbootclasspath/p:$BLINKY_JAR -javaagent:$BLINKY_JAR="

INPUT1="FOUNTAIN-5-2-16-nyt.txt"
INPUT2="pride-and-prejudice.txt"

CONFIGS=("0" \
      "l,frames,calldepth" \
      "i,frames,calldepth" \
      "e,frames,calldepth" \
      "x,frames,calldepth" \
      "xile,frames,calldepth" \
      "z,frames,calldepth" \
      "f,frames,calldepth" \
      "v,frames,calldepth" \
      "c,frames,calldepth" \
      "j,frames,calldepth" \
      "s,frames,calldepth" \
      "t,frames,calldepth" \
      "A,frames,calldepth" )
      
MAINS=( )
#IFS=""

for MAIN in "Namaste" \
  "SummaryLib 1" \
  "SummaryLib 2" \
  "SummaryLib 3" \
  "SummaryLib 4" \
  "SummaryLib 5" \
  "SummaryLib 6" \
  "styleEx.CandyFactory" \
  "styleEx.CookBook" \
  "styleEx.DeclaredIntentions" \
  "styleEx.Hollywood" \
  "styleEx.Quarantine" \
  "styleEx.TheOne"; do
  
  
  SUBJECT=${BOLD}"$MAIN"${NORMAL}
  
  echo $SUBJECT
  echo -ne "🏃 running $SUBJECT with java"
  systime="$(TIMEFORMAT='%S';time ( java -cp .:$DIAGNOSTICS_JAR "$SUBJECTS_PKG."$MAIN > /dev/null 2>&1 ) 2>&1 1>/dev/null )"
  echo " ==> $systime sec"
  
  echo "🏃 running $SUBJECT with 🌟 blinky"
  for CONFIG in ${CONFIGS[@]}; do
    echo -ne "👉 with configuration: $CONFIG"
    systime="$(TIMEFORMAT='%S';time ( java $BLINKY$CONFIG -cp .:$DIAGNOSTICS_JAR "$SUBJECTS_PKG."$MAIN > /dev/null 2>&1 ) 2>&1 1>/dev/null )"
    echo " ==> $systime sec"
  done
done

exit $?

function check {
  ls -alh $1/*trc
  grep "Caused" $1/*err

  for trace in $(ls $1/*trc); do
    echo $trace
    grep '\$\$\$' $trace | wc -l
  done
}

#check traces
#check traces-full
